fixed issues with systemd config and shell bin scripts
fixed issue with instance_info adding all stdout to info file :(

added user data for packer instance to help with coreos startup tasks

diff --git a/coreos/aws/uploads/home_dir_assets/core/bin/instance_info b/coreos/aws/uploads/home_dir_assets/core/bin/instance_info
--- a/coreos/aws/uploads/home_dir_assets/core/bin/instance_info
+++ b/coreos/aws/uploads/home_dir_assets/core/bin/instance_info
@@ -9,6 +9,11 @@
 # i.e. we're not interested in those metadata or tag values
 # that are subject to change during the lifestyle of the instance.
 #
+if ! . ~/bin/functions >/dev/null 2>&1
+then
+    echo "$0 ERROR: couldn't source custom shell functions [~/bin/functions]"
+    exit 1
+fi
 INFO_FILE=/etc/eurostar/instance_info
 TIMESTAMP="$(date +'%Y-%m-%d %H:%M:%S')"
 
